허깅 페이스
https://huggingface.co/models

-- 가상환경을 먼저 만들고 해당 라이브러리를 새로 설치함

- pip install tensorflow==2.15.0
- pip install transformers==4.38.0
- pip install jupyter
- pip install torch torchvision --index-url https://download.pytorch.org/whl/cu129
- pip install pandas
- pip install matplotlib
- pip install seaborn
- pip install scikit-learn

-- transformer 하고 tensorflow가 버전에 따라 호환이 안되어서 새로운 가상환경을 만들어서 새롭게 라이브러리를 설치해 주었다!

In [4]:
import pandas as pd
from transformers import BertTokenizer

In [5]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

C:\Project\Project_source\NLP_BERT\.venv\Lib\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

C:\Project\Project_source\NLP_BERT\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Win11Pro\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [6]:
result = tokenizer.tokenize("Here is the sentence I want embeddings for.")
print(result)

['here', 'is', 'the', 'sentence', 'i', 'want', 'em', '##bed', '##ding', '##s', 'for', '.']

In [7]:
tokenizer.vocab

OrderedDict([('[PAD]', 0),
             ('[unused0]', 1),
             ('[unused1]', 2),
             ('[unused2]', 3),
             ('[unused3]', 4),
             ('[unused4]', 5),
             ('[unused5]', 6),
             ('[unused6]', 7),
             ('[unused7]', 8),
             ('[unused8]', 9),
             ('[unused9]', 10),
             ('[unused10]', 11),
             ('[unused11]', 12),
             ('[unused12]', 13),
             ('[unused13]', 14),
             ('[unused14]', 15),
             ('[unused15]', 16),
             ('[unused16]', 17),
             ('[unused17]', 18),
             ('[unused18]', 19),
             ('[unused19]', 20),
             ('[unused20]', 21),
             ('[unused21]', 22),
             ('[unused22]', 23),
             ('[unused23]', 24),
             ('[unused24]', 25),
             ('[unused25]', 26),
             ('[unused26]', 27),
             ('[unused27]', 28),
             ('[unused28]', 29),
             ('[unused29]', 30),
             ('[unused30]', 31),
             ('[unused31]', 32),
             ('[unused32]', 33),
             ('[unused33]', 34),
             ('[unused34]', 35),
             ('[unused35]', 36),
             ('[unused36]', 37),
             ('[unused37]', 38),
             ('[unused38]', 39),
             ('[unused39]', 40),
             ('[unused40]', 41),
             ('[unused41]', 42),
             ('[unused42]', 43),
             ('[unused43]', 44),
             ('[unused44]', 45),
             ('[unused45]', 46),
             ('[unused46]', 47),
             ('[unused47]', 48),
             ('[unused48]', 49),
             ('[unused49]', 50),
             ('[unused50]', 51),
             ('[unused51]', 52),
             ('[unused52]', 53),
             ('[unused53]', 54),
             ('[unused54]', 55),
             ('[unused55]', 56),
             ('[unused56]', 57),
             ('[unused57]', 58),
             ('[unused58]', 59),
             ('[unused59]', 60),
             ('[unused60]', 61),
             ('[unused61]', 62),
             ('[unused62]', 63),
             ('[unused63]', 64),
             ('[unused64]', 65),
             ('[unused65]', 66),
             ('[unused66]', 67),
             ('[unused67]', 68),
             ('[unused68]', 69),
             ('[unused69]', 70),
             ('[unused70]', 71),
             ('[unused71]', 72),
             ('[unused72]', 73),
             ('[unused73]', 74),
             ('[unused74]', 75),
             ('[unused75]', 76),
             ('[unused76]', 77),
             ('[unused77]', 78),
             ('[unused78]', 79),
             ('[unused79]', 80),
             ('[unused80]', 81),
             ('[unused81]', 82),
             ('[unused82]', 83),
             ('[unused83]', 84),
             ('[unused84]', 85),
             ('[unused85]', 86),
             ('[unused86]', 87),
             ('[unused87]', 88),
             ('[unused88]', 89),
             ('[unused89]', 90),
             ('[unused90]', 91),
             ('[unused91]', 92),
             ('[unused92]', 93),
             ('[unused93]', 94),
             ('[unused94]', 95),
             ('[unused95]', 96),
             ('[unused96]', 97),
             ('[unused97]', 98),
             ('[unused98]', 99),
             ('[UNK]', 100),
             ('[CLS]', 101),
             ('[SEP]', 102),
             ('[MASK]', 103),
             ('[unused99]', 104),
             ('[unused100]', 105),
             ('[unused101]', 106),
             ('[unused102]', 107),
             ('[unused103]', 108),
             ('[unused104]', 109),
             ('[unused105]', 110),
             ('[unused106]', 111),
             ('[unused107]', 112),
             ('[unused108]', 113),
             ('[unused109]', 114),
             ('[unused110]', 115),
             ('[unused111]', 116),
             ('[unused112]', 117),
             ('[unused113]', 118),
             ('[unused114]', 119),
             ('[unused115]', 120),
             ('[unused116]', 121),
             ('[unused117]', 122),
             ('[unused118]', 123),
             ('[unused119]', 124),
             ('[unused120]', 125),
             ('[unused121]', 126),
             ('[unused122]', 127),
             ('[unused123]', 128),
             ('[unused124]', 129),
             ('[unused125]', 130),
             ('[unused126]', 131),
             ('[unused127]', 132),
             ('[unused128]', 133),
             ('[unused129]', 134),
             ('[unused130]', 135),
             ('[unused131]', 136),
             ('[unused132]', 137),
             ('[unused133]', 138),
             ('[unused134]', 139),
             ('[unused135]', 140),
             ('[unused136]', 141),
             ('[unused137]', 142),
             ('[unused138]', 143),
             ('[unused139]', 144),
             ('[unused140]', 145),
             ('[unused141]', 146),
             ('[unused142]', 147),
             ('[unused143]', 148),
             ('[unused144]', 149),
             ('[unused145]', 150),
             ('[unused146]', 151),
             ('[unused147]', 152),
             ('[unused148]', 153),
             ('[unused149]', 154),
             ('[unused150]', 155),
             ('[unused151]', 156),
             ('[unused152]', 157),
             ('[unused153]', 158),
             ('[unused154]', 159),
             ('[unused155]', 160),
             ('[unused156]', 161),
             ('[unused157]', 162),
             ('[unused158]', 163),
             ('[unused159]', 164),
             ('[unused160]', 165),
             ('[unused161]', 166),
             ('[unused162]', 167),
             ('[unused163]', 168),
             ('[unused164]', 169),
             ('[unused165]', 170),
             ('[unused166]', 171),
             ('[unused167]', 172),
             ('[unused168]', 173),
             ('[unused169]', 174),
             ('[unused170]', 175),
             ('[unused171]', 176),
             ('[unused172]', 177),
             ('[unused173]', 178),
             ('[unused174]', 179),
             ('[unused175]', 180),
             ('[unused176]', 181),
             ('[unused177]', 182),
             ('[unused178]', 183),
             ('[unused179]', 184),
             ('[unused180]', 185),
             ('[unused181]', 186),
             ('[unused182]', 187),
             ('[unused183]', 188),
             ('[unused184]', 189),
             ('[unused185]', 190),
             ('[unused186]', 191),
             ('[unused187]', 192),
             ('[unused188]', 193),
             ('[unused189]', 194),
             ('[unused190]', 195),
             ('[unused191]', 196),
             ('[unused192]', 197),
             ('[unused193]', 198),
             ('[unused194]', 199),
             ('[unused195]', 200),
             ('[unused196]', 201),
             ('[unused197]', 202),
             ('[unused198]', 203),
             ('[unused199]', 204),
             ('[unused200]', 205),
             ('[unused201]', 206),
             ('[unused202]', 207),
             ('[unused203]', 208),
             ('[unused204]', 209),
             ('[unused205]', 210),
             ('[unused206]', 211),
             ('[unused207]', 212),
             ('[unused208]', 213),
             ('[unused209]', 214),
             ('[unused210]', 215),
             ('[unused211]', 216),
             ('[unused212]', 217),
             ('[unused213]', 218),
             ('[unused214]', 219),
             ('[unused215]', 220),
             ('[unused216]', 221),
             ('[unused217]', 222),
             ('[unused218]', 223),
             ('[unused219]', 224),
             ('[unused220]', 225),
             ('[unused221]', 226),
             ('[unused222]', 227),
             ('[unused223]', 228),
             ('[unused224]', 229),
             ('[unused225]', 230),
             ('[unused226]', 231),
             ('[unused227]', 232),
             ('[unused228]', 233),
             ('[unused229]', 234),
             ('[unused230]', 235),
             ('[unused231]', 236),
             ('[unused232]', 237),
             ('[unused233]', 238),
             ('[unused234]', 239),
             ('[unused235]', 240),
             ('[unused236]', 241),
             ('[unused237]', 242),
             ('[unused238]', 243),
             ('[unused239]', 244),
             ('[unused240]', 245),
             ('[unused241]', 246),
             ('[unused242]', 247),
             ('[unused243]', 248),
             ('[unused244]', 249),
             ('[unused245]', 250),
             ('[unused246]', 251),
             ('[unused247]', 252),
             ('[unused248]', 253),
             ('[unused249]', 254),
             ('[unused250]', 255),
             ('[unused251]', 256),
             ('[unused252]', 257),
             ('[unused253]', 258),
             ('[unused254]', 259),
             ('[unused255]', 260),
             ('[unused256]', 261),
             ('[unused257]', 262),
             ('[unused258]', 263),
             ('[unused259]', 264),
             ('[unused260]', 265),
             ('[unused261]', 266),
             ('[unused262]', 267),
             ('[unused263]', 268),
             ('[unused264]', 269),
             ('[unused265]', 270),
             ('[unused266]', 271),
             ('[unused267]', 272),
             ('[unused268]', 273),
             ('[unused269]', 274),
             ('[unused270]', 275),
             ('[unused271]', 276),
             ('[unused272]', 277),
             ('[unused273]', 278),
             ('[unused274]', 279),
             ('[unused275]', 280),
             ('[unused276]', 281),
             ('[unused277]', 282),
             ('[unused278]', 283),
             ('[unused279]', 284),
             ('[unused280]', 285),
             ('[unused281]', 286),
             ('[unused282]', 287),
             ('[unused283]', 288),
             ('[unused284]', 289),
             ('[unused285]', 290),
             ('[unused286]', 291),
             ('[unused287]', 292),
             ('[unused288]', 293),
             ('[unused289]', 294),
             ('[unused290]', 295),
             ('[unused291]', 296),
             ('[unused292]', 297),
             ('[unused293]', 298),
             ('[unused294]', 299),
             ('[unused295]', 300),
             ('[unused296]', 301),
             ('[unused297]', 302),
             ('[unused298]', 303),
             ('[unused299]', 304),
             ('[unused300]', 305),
             ('[unused301]', 306),
             ('[unused302]', 307),
             ('[unused303]', 308),
             ('[unused304]', 309),
             ('[unused305]', 310),
             ('[unused306]', 311),
             ('[unused307]', 312),
             ('[unused308]', 313),
             ('[unused309]', 314),
             ('[unused310]', 315),
             ('[unused311]', 316),
             ('[unused312]', 317),
             ('[unused313]', 318),
             ('[unused314]', 319),
             ('[unused315]', 320),
             ('[unused316]', 321),
             ('[unused317]', 322),
             ('[unused318]', 323),
             ('[unused319]', 324),
             ('[unused320]', 325),
             ('[unused321]', 326),
             ('[unused322]', 327),
             ('[unused323]', 328),
             ('[unused324]', 329),
             ('[unused325]', 330),
             ('[unused326]', 331),
             ('[unused327]', 332),
             ('[unused328]', 333),
             ('[unused329]', 334),
             ('[unused330]', 335),
             ('[unused331]', 336),
             ('[unused332]', 337),
             ('[unused333]', 338),
             ('[unused334]', 339),
             ('[unused335]', 340),
             ('[unused336]', 341),
             ('[unused337]', 342),
             ('[unused338]', 343),
             ('[unused339]', 344),
             ('[unused340]', 345),
             ('[unused341]', 346),
             ('[unused342]', 347),
             ('[unused343]', 348),
             ('[unused344]', 349),
             ('[unused345]', 350),
             ('[unused346]', 351),
             ('[unused347]', 352),
             ('[unused348]', 353),
             ('[unused349]', 354),
             ('[unused350]', 355),
             ('[unused351]', 356),
             ('[unused352]', 357),
             ('[unused353]', 358),
             ('[unused354]', 359),
             ('[unused355]', 360),
             ('[unused356]', 361),
             ('[unused357]', 362),
             ('[unused358]', 363),
             ('[unused359]', 364),
             ('[unused360]', 365),
             ('[unused361]', 366),
             ('[unused362]', 367),
             ('[unused363]', 368),
             ('[unused364]', 369),
             ('[unused365]', 370),
             ('[unused366]', 371),
             ('[unused367]', 372),
             ('[unused368]', 373),
             ('[unused369]', 374),
             ('[unused370]', 375),
             ('[unused371]', 376),
             ('[unused372]', 377),
             ('[unused373]', 378),
             ('[unused374]', 379),
             ('[unused375]', 380),
             ('[unused376]', 381),
             ('[unused377]', 382),
             ('[unused378]', 383),
             ('[unused379]', 384),
             ('[unused380]', 385),
             ('[unused381]', 386),
             ('[unused382]', 387),
             ('[unused383]', 388),
             ('[unused384]', 389),
             ('[unused385]', 390),
             ('[unused386]', 391),
             ('[unused387]', 392),
             ('[unused388]', 393),
             ('[unused389]', 394),
             ('[unused390]', 395),
             ('[unused391]', 396),
             ('[unused392]', 397),
             ('[unused393]', 398),
             ('[unused394]', 399),
             ('[unused395]', 400),
             ('[unused396]', 401),
             ('[unused397]', 402),
             ('[unused398]', 403),
             ('[unused399]', 404),
             ('[unused400]', 405),
             ('[unused401]', 406),
             ('[unused402]', 407),
             ('[unused403]', 408),
             ('[unused404]', 409),
             ('[unused405]', 410),
             ('[unused406]', 411),
             ('[unused407]', 412),
             ('[unused408]', 413),
             ('[unused409]', 414),
             ('[unused410]', 415),
             ('[unused411]', 416),
             ('[unused412]', 417),
             ('[unused413]', 418),
             ('[unused414]', 419),
             ('[unused415]', 420),
             ('[unused416]', 421),
             ('[unused417]', 422),
             ('[unused418]', 423),
             ('[unused419]', 424),
             ('[unused420]', 425),
             ('[unused421]', 426),
             ('[unused422]', 427),
             ('[unused423]', 428),
             ('[unused424]', 429),
             ('[unused425]', 430),
             ('[unused426]', 431),
             ('[unused427]', 432),
             ('[unused428]', 433),
             ('[unused429]', 434),
             ('[unused430]', 435),
             ('[unused431]', 436),
             ('[unused432]', 437),
             ('[unused433]', 438),
             ('[unused434]', 439),
             ('[unused435]', 440),
             ('[unused436]', 441),
             ('[unused437]', 442),
             ('[unused438]', 443),
             ('[unused439]', 444),
             ('[unused440]', 445),
             ('[unused441]', 446),
             ('[unused442]', 447),
             ('[unused443]', 448),
             ('[unused444]', 449),
             ('[unused445]', 450),
             ('[unused446]', 451),
             ('[unused447]', 452),
             ('[unused448]', 453),
             ('[unused449]', 454),
             ('[unused450]', 455),
             ('[unused451]', 456),
             ('[unused452]', 457),
             ('[unused453]', 458),
             ('[unused454]', 459),
             ('[unused455]', 460),
             ('[unused456]', 461),
             ('[unused457]', 462),
             ('[unused458]', 463),
             ('[unused459]', 464),
             ('[unused460]', 465),
             ('[unused461]', 466),
             ('[unused462]', 467),
             ('[unused463]', 468),
             ('[unused464]', 469),
             ('[unused465]', 470),
             ('[unused466]', 471),
             ('[unused467]', 472),
             ('[unused468]', 473),
             ('[unused469]', 474),
             ('[unused470]', 475),
             ('[unused471]', 476),
             ('[unused472]', 477),
             ('[unused473]', 478),
             ('[unused474]', 479),
             ('[unused475]', 480),
             ('[unused476]', 481),
             ('[unused477]', 482),
             ('[unused478]', 483),
             ('[unused479]', 484),
             ('[unused480]', 485),
             ('[unused481]', 486),
             ('[unused482]', 487),
             ('[unused483]', 488),
             ('[unused484]', 489),
             ('[unused485]', 490),
             ('[unused486]', 491),
             ('[unused487]', 492),
             ('[unused488]', 493),
             ('[unused489]', 494),
             ('[unused490]', 495),
             ('[unused491]', 496),
             ('[unused492]', 497),
             ('[unused493]', 498),
             ('[unused494]', 499),
             ('[unused495]', 500),
             ('[unused496]', 501),
             ('[unused497]', 502),
             ('[unused498]', 503),
             ('[unused499]', 504),
             ('[unused500]', 505),
             ('[unused501]', 506),
             ('[unused502]', 507),
             ('[unused503]', 508),
             ('[unused504]', 509),
             ('[unused505]', 510),
             ('[unused506]', 511),
             ('[unused507]', 512),
             ('[unused508]', 513),
             ('[unused509]', 514),
             ('[unused510]', 515),
             ('[unused511]', 516),
             ('[unused512]', 517),
             ('[unused513]', 518),
             ('[unused514]', 519),
             ('[unused515]', 520),
             ('[unused516]', 521),
             ('[unused517]', 522),
             ('[unused518]', 523),
             ('[unused519]', 524),
             ('[unused520]', 525),
             ('[unused521]', 526),
             ('[unused522]', 527),
             ('[unused523]', 528),
             ('[unused524]', 529),
             ('[unused525]', 530),
             ('[unused526]', 531),
             ('[unused527]', 532),
             ('[unused528]', 533),
             ('[unused529]', 534),
             ('[unused530]', 535),
             ('[unused531]', 536),
             ('[unused532]', 537),
             ('[unused533]', 538),
             ('[unused534]', 539),
             ('[unused535]', 540),
             ('[unused536]', 541),
             ('[unused537]', 542),
             ('[unused538]', 543),
             ('[unused539]', 544),
             ('[unused540]', 545),
             ('[unused541]', 546),
             ('[unused542]', 547),
             ('[unused543]', 548),
             ('[unused544]', 549),
             ('[unused545]', 550),
             ('[unused546]', 551),
             ('[unused547]', 552),
             ('[unused548]', 553),
             ('[unused549]', 554),
             ('[unused550]', 555),
             ('[unused551]', 556),
             ('[unused552]', 557),
             ('[unused553]', 558),
             ('[unused554]', 559),
             ('[unused555]', 560),
             ('[unused556]', 561),
             ('[unused557]', 562),
             ('[unused558]', 563),
             ('[unused559]', 564),
             ('[unused560]', 565),
             ('[unused561]', 566),
             ('[unused562]', 567),
             ('[unused563]', 568),
             ('[unused564]', 569),
             ('[unused565]', 570),
             ('[unused566]', 571),
             ('[unused567]', 572),
             ('[unused568]', 573),
             ('[unused569]', 574),
             ('[unused570]', 575),
             ('[unused571]', 576),
             ('[unused572]', 577),

In [8]:
print(tokenizer.vocab['here'])

2182

In [11]:
# 키 에러 발생
# print(tokenizer.vocab['embeddings'])

# 없는 단어라서 에러가 발생하고 서브워드를 만들어서 저장함

In [12]:
# 없는 단어를 서브워드만들어서 저장하는 작업
print(tokenizer.vocab['em'])

7861

In [13]:
# 없는 단어를 서브워드만들어서 저장하는 작업
print(tokenizer.vocab['##bed'])

8270

In [14]:
# 데이터 값을 확인하는 작업 # 키를 불러와서 데이터를 확인
with open('vocabulary.txt', 'w', encoding='utf-8') as f:
    for token in tokenizer.vocab.keys():
        f.write(token + '\n')

In [18]:
# 데이터 프레임으로 확인하는 방법
df = pd.read_fwf('vocabulary.txt', header=None)  # 일정한 간격, 고정된 폭 구조의 외부데이터 로드
df

# fix width file = 고정된 너비로 부터 파일을 읽어올 때 쓰는 함수

               0
0          [PAD]
1      [unused0]
2      [unused1]
3      [unused2]
4      [unused3]
...          ...
30517        ##．
30518        ##／
30519        ##：
30520        ##？
30521        ##～

[30522 rows x 1 columns]

In [19]:
# 3만개의 단어로 구성되있다!!
print('단어 집합의 크기 : ', len(df))

단어 집합의 크기 :  30522

In [21]:
df.loc[4667].values[0]

'##ding'

In [22]:
df.loc[102].values[0]

'[SEP]'

-- 여기까지 없는 단어는 서브 워드를 만들어서 확인하는 작업을 했음

In [23]:
from transformers import TFBertForMaskedLM
from transformers import AutoTokenizer

WARNING:tensorflow:From C:\Project\Project_source\NLP_BERT\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [24]:
model = TFBertForMaskedLM.from_pretrained('bert-large-uncased') # uncased : 학습을 할 때 전부 소문자로 변경해서 학습에 활용한다. # mask : mask된 위치를 학습 할 수 있는 모델 이 현재 이 모델이다
tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased')

C:\Project\Project_source\NLP_BERT\.venv\Lib\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

C:\Project\Project_source\NLP_BERT\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Win11Pro\.cache\huggingface\hub\models--bert-large-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

WARNING:tensorflow:From C:\Project\Project_source\NLP_BERT\.venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

All PyTorch model weights were used when initializing TFBertForMaskedLM.

All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [25]:
# 토큰 생성

inputs = tokenizer("Soccer is a really fun [MASK].", return_tensors='tf')

In [35]:
## input_ids 단어의 인코딩 된 인덱스 값

# 생성된 토큰의 정수값을 확인 # 단어의 인코딩된 인덱스 값
# 현재 이렇게 인코딩
print(inputs['input_ids'])

tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)

In [36]:
## token_type_ids

# sentence 임베딩 벡터 이다 . 센텐스에 대한 벡터값을 확인
print(inputs['token_type_ids'])

tf.Tensor([[0 0 0 0 0 0 0 0 0]], shape=(1, 9), dtype=int32)

In [37]:
## attention_mask

# 패딩 여부를 채크하는 것  패딩이 아닌 것은 0으로 체크된다  >>> 이렇게 하는 이유는 학습을 시킬지 말지 결정한다.
print(inputs['attention_mask'])

tf.Tensor([[1 1 1 1 1 1 1 1 1]], shape=(1, 9), dtype=int32)

마스킹된 단어를 예측하고 대체할 수 있는 파이프 라인

In [39]:
# Transformers 라이브러리를 사용하여 문장 내에서 마스킹된 단어를 예측하고 대체할 수 있는 파이프 라인
from transformers import FillMaskPipeline

pip = FillMaskPipeline(model=model, tokenizer=tokenizer)

In [40]:
# 여기에 들어가는 단어를 예측해준다.
pip("Soccer is a really fun [MASK].")

[{'score': 0.7621223330497742,
  'token': 4368,
  'token_str': 'sport',
  'sequence': 'soccer is a really fun sport.'},
 {'score': 0.20342253148555756,
  'token': 2208,
  'token_str': 'game',
  'sequence': 'soccer is a really fun game.'},
 {'score': 0.012208692729473114,
  'token': 2518,
  'token_str': 'thing',
  'sequence': 'soccer is a really fun thing.'},
 {'score': 0.0018630481790751219,
  'token': 4023,
  'token_str': 'activity',
  'sequence': 'soccer is a really fun activity.'},
 {'score': 0.001335500623099506,
  'token': 2492,
  'token_str': 'field',
  'sequence': 'soccer is a really fun field.'}]

In [41]:
pip('The Avergers is a really fun [MASK]')

[{'score': 0.6736562848091125,
  'token': 1012,
  'token_str': '.',
  'sequence': 'the avergers is a really fun.'},
 {'score': 0.2904200553894043,
  'token': 999,
  'token_str': '!',
  'sequence': 'the avergers is a really fun!'},
 {'score': 0.027257775887846947,
  'token': 1025,
  'token_str': ';',
  'sequence': 'the avergers is a really fun ;'},
 {'score': 0.007939246483147144,
  'token': 1029,
  'token_str': '?',
  'sequence': 'the avergers is a really fun?'},
 {'score': 0.0002482402487657964,
  'token': 2133,
  'token_str': '...',
  'sequence': 'the avergers is a really fun...'}]

In [43]:
pip('I went to [MASK] this morning.')

[{'score': 0.3573072850704193,
  'token': 2147,
  'token_str': 'work',
  'sequence': 'i went to work this morning.'},
 {'score': 0.2330455183982849,
  'token': 2793,
  'token_str': 'bed',
  'sequence': 'i went to bed this morning.'},
 {'score': 0.12845079600811005,
  'token': 2082,
  'token_str': 'school',
  'sequence': 'i went to school this morning.'},
 {'score': 0.06230589747428894,
  'token': 3637,
  'token_str': 'sleep',
  'sequence': 'i went to sleep this morning.'},
 {'score': 0.0469527542591095,
  'token': 2465,
  'token_str': 'class',
  'sequence': 'i went to class this morning.'}]

이제 한글로 확인해보자

# 한국어 BERT의 마스크드 언어 모델 실습

In [45]:
from transformers import TFBertForMaskedLM
from transformers import AutoTokenizer

In [46]:
model = TFBertForMaskedLM.from_pretrained('klue/bert-base', from_pt=True) 
# from_pt의 pt는 파이토치의 약자로 파이토치 모델을 가져와서 쓴다는 의미 # 파이토치 모델을 텐스플로 모델의 환경에서 사용하고 싶을 때 사용

tokenizer = AutoTokenizer.from_pretrained('klue/bert-base')

config.json:   0%|          | 0.00/425 [00:00<?, ?B/s]

C:\Project\Project_source\NLP_BERT\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Win11Pro\.cache\huggingface\hub\models--klue--bert-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

pytorch_model.bin:   0%|          | 0.00/445M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForMaskedLM: ['bert.embeddings.position_ids', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing TFBertForMaskedLM from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForMaskedLM from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.

tokenizer_config.json:   0%|          | 0.00/289 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

In [47]:
inputs = tokenizer("축구는 정말 재미있는 [MASK]다.", return_tensors='tf')

In [49]:
## input_ids 단어의 인코딩 된 인덱스 값

# 생성된 토큰의 정수값을 확인 # 단어의 인코딩된 인덱스 값
# 현재 이렇게 인코딩
print(inputs['input_ids'])

tf.Tensor([[   2 4713 2259 3944 6001 2259    4  809   18    3]], shape=(1, 10), dtype=int32)

In [50]:
# sentence 인코딩 값
print(inputs['token_type_ids'])

tf.Tensor([[0 0 0 0 0 0 0 0 0 0]], shape=(1, 10), dtype=int32)

In [54]:
## attention_mask

# 패딩 여부를 채크하는 것  패딩이 아닌 것은 0으로 체크된다  >>> 이렇게 하는 이유는 학습을 시킬지 말지 결정한다.
print(inputs['attention_mask'])

tf.Tensor([[1 1 1 1 1 1 1 1 1 1]], shape=(1, 10), dtype=int32)

In [52]:
from transformers import FillMaskPipeline

pip = FillMaskPipeline(model=model, tokenizer=tokenizer)

In [53]:
pip('축구는 정말 재미있는 [MASK]다.')

[{'score': 0.8963630199432373,
  'token': 4559,
  'token_str': '스포츠',
  'sequence': '축구는 정말 재미있는 스포츠 다.'},
 {'score': 0.025957956910133362,
  'token': 568,
  'token_str': '거',
  'sequence': '축구는 정말 재미있는 거 다.'},
 {'score': 0.010034089908003807,
  'token': 3682,
  'token_str': '경기',
  'sequence': '축구는 정말 재미있는 경기 다.'},
 {'score': 0.007924494333565235,
  'token': 4713,
  'token_str': '축구',
  'sequence': '축구는 정말 재미있는 축구 다.'},
 {'score': 0.007844340987503529,
  'token': 5845,
  'token_str': '놀이',
  'sequence': '축구는 정말 재미있는 놀이 다.'}]

In [56]:
pip("나는 오늘 아침에 [MASK]에 출근을 했다.")

[{'score': 0.080125592648983,
  'token': 3769,
  'token_str': '회사',
  'sequence': '나는 오늘 아침에 회사 에 출근을 했다.'},
 {'score': 0.061240628361701965,
  'token': 1,
  'token_str': '[UNK]',
  'sequence': '나는 오늘 아침에 에 출근을 했다.'},
 {'score': 0.01748664677143097,
  'token': 4345,
  'token_str': '공장',
  'sequence': '나는 오늘 아침에 공장 에 출근을 했다.'},
 {'score': 0.01613180711865425,
  'token': 5841,
  'token_str': '사무실',
  'sequence': '나는 오늘 아침에 사무실 에 출근을 했다.'},
 {'score': 0.015360811725258827,
  'token': 3671,
  'token_str': '서울',
  'sequence': '나는 오늘 아침에 서울 에 출근을 했다.'}]

# 구글 BERT의 다음 문장 예측 실습

In [57]:
import tensorflow as tf
from transformers import TFBertForNextSentencePrediction
from transformers import AutoTokenizer

In [58]:
model = TFBertForNextSentencePrediction.from_pretrained('bert-base-uncased')
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFBertForNextSentencePrediction.

All the weights of TFBertForNextSentencePrediction were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForNextSentencePrediction for predictions without further training.

In [59]:
prompt = "In Italy, pizza served in formal settings, such as at a restaurant, is presented unsliced."
next_sentence = "pizza is eaten with the use of a knife and fork. In casual settings, however, it is cut into wedges to be eaten while held in the hand."

In [61]:
# 위 문장을가지고 토큰을 생성해 보자

encoding = tokenizer(prompt, next_sentence, return_tensors='tf')

In [64]:
print(encoding['input_ids']) # 102가 SEP로 구분자의 역할을 나타낸다

tf.Tensor(
[[  101  1999  3304  1010 10733  2366  1999  5337 10906  1010  2107  2004
   2012  1037  4825  1010  2003  3591  4895 14540  6610  2094  1012   102
  10733  2003  8828  2007  1996  2224  1997  1037  5442  1998  9292  1012
   1999 10017 10906  1010  2174  1010  2009  2003  3013  2046 17632  2015
   2000  2022  8828  2096  2218  1999  1996  2192  1012   102]], shape=(1, 58), dtype=int32)

In [69]:
# 특수문자인 구분자를 확인하는 코드!
print(tokenizer.cls_token, ':', tokenizer.cls_token_id)
print(tokenizer.sep_token, ':', tokenizer.sep_token_id)

[CLS] : 101
[SEP] : 102

In [73]:
# 현재 문장에서 cls sep가 어디 위치에 있는지 확인하는 코드
# 즉 숫자로된 내용을 다시 디코딩 하는 코드
print(tokenizer.decode(encoding['input_ids'][0]))

[CLS] in italy, pizza served in formal settings, such as at a restaurant, is presented unsliced. [SEP] pizza is eaten with the use of a knife and fork. in casual settings, however, it is cut into wedges to be eaten while held in the hand. [SEP]

In [74]:
# sentence 을 구분할 수 있는 값이 : type_ids 이다.
# 문장 sentence를 숫자로 표현된것을 보고 확인하는 작업

print(encoding['token_type_ids'])

tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]], shape=(1, 58), dtype=int32)

In [75]:
# 이제 예측을 해보자!!!~

In [77]:
# 인코딩한 값과 , 문장 센텐스를 입력해서 
# softmax를 실행해서 확률값을 나타낸다.

logits = model(encoding['input_ids'], token_type_ids=encoding['token_type_ids'])[0]
softmax = tf.keras.layers.Softmax()
probs = softmax(logits)
print(probs)

tf.Tensor([[9.9999714e-01 2.8381860e-06]], shape=(1, 2), dtype=float32)

In [ ]:
# 이어지는 문장이면 0 아니면 1이 나오게 된다.
# 위 결과를정리해보면

In [78]:
# 가장 큰값의 위치를 tensorflow 를 사용해줬기에 numpy() 함수를 통해서 배열을 변환해준다.

print("최종 예측 레이블 :", tf.math.argmax(probs, axis=-1).numpy())

최종 예측 레이블 : [0]

In [79]:
# 즉, 위의 예제에서 첫째문장과 둘 때 문장이 연관성이 있다는 의미가 된다

In [ ]:
### 이제 연관성이 없는 예제도 해보자

In [80]:
prompt = "In Italy, pizza served in formal settings, such as at a restaurant, is presented unsliced."
next_sentence = "The sky is blue due to the shorter wavelength of blue light."
encoding = tokenizer(prompt, next_sentence, return_tensors='tf')

logits = model(encoding['input_ids'], token_type_ids=encoding['token_type_ids'])[0]

softmax = tf.keras.layers.Softmax()
probs = softmax(logits)
print("최종 예측 레이블 :", tf.math.argmax(probs, axis=-1).numpy())

최종 예측 레이블 : [1]

In [81]:
# 이렇게 영어로 한것처럼 한국어로 예측을 할 수 있다.!!!

# 한국어 BERT의 다음 문장 얘측

In [83]:
import tensorflow as tf
from transformers import TFBertForNextSentencePrediction
from transformers import AutoTokenizer

In [84]:
model = TFBertForNextSentencePrediction.from_pretrained('klue/bert-base', from_pt=True)
tokenizer = AutoTokenizer.from_pretrained('klue/bert-base')

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForNextSentencePrediction: ['bert.embeddings.position_ids']
- This IS expected if you are initializing TFBertForNextSentencePrediction from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForNextSentencePrediction from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertForNextSentencePrediction were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForNextSentencePrediction for predictions without further training.

In [89]:
# 상관있는 예제

prompt = "2022년 월드컵 축ㄱ대회는 일본과 공동으로 개최되었던 세계적인 큰 잔치입니다."
next_sentence = "여행을 가보니 한국의 2002년 월드컵 축구대회의 준비는 완벽했습니다."
encoding = tokenizer(prompt, next_sentence, return_tensors='tf')

logits = model(encoding['input_ids'], token_type_ids=encoding['token_type_ids'])[0]

softmax = tf.keras.layers.Softmax()
probs = softmax(logits)
print("최종 예측 레이블 :", tf.math.argmax(probs, axis=-1).numpy())

최종 예측 레이블 : [0]

In [90]:
# 상관없는 예제

prompt = "2022년 월드컵 축ㄱ대회는 일본과 공동으로 개최되었던 세계적인 큰 잔치입니다."
next_sentence = "극장가서 로맨스 영화를 보고싶어요."
encoding = tokenizer(prompt, next_sentence, return_tensors='tf')

logits = model(encoding['input_ids'], token_type_ids=encoding['token_type_ids'])[0]

softmax = tf.keras.layers.Softmax()
probs = softmax(logits)
print("최종 예측 레이블 :", tf.math.argmax(probs, axis=-1).numpy())

최종 예측 레이블 : [1]

In [87]:
# 여기까지가 next_sentence와 관련된 문장이다!!

# KoBERT를 이용한 네이버 영화 리뷰 분류

In [91]:
import transformers

transformers.__version__

'4.38.0'

In [92]:
import pandas as pd
import numpy as np
import urllib.request
import os
from tqdm import tqdm
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel

In [93]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings_train.txt", filename="ratings_train.txt")
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings_test.txt", filename="ratings_test.txt")

('ratings_test.txt', <http.client.HTTPMessage at 0x2d4cf98ffd0>)

In [97]:
train_data = pd.read_table("ratings_train.txt")
test_data = pd.read_table("ratings_test.txt")

In [98]:
print("훈련용 리뷰 개수 :", len(train_data))

훈련용 리뷰 개수 : 150000

In [99]:
print("테스트용 리뷰 개수 :", len(test_data))

테스트용 리뷰 개수 : 50000

In [103]:
train_data[:10] # 1이 긍정 0이 부정

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
5   5403919      막 걸음마 뗀 3세부터 초등학교 1학년생인 8살용영화.ㅋㅋㅋ...별반개도 아까움.      0
6   7797314                              원작의 긴장감을 제대로 살려내지못했다.      0
7   9443947  별 반개도 아깝다 욕나온다 이응경 길용우 연기생활이몇년인지..정말 발로해도 그것보단...      0
8   7156791                             액션이 없는데도 재미 있는 몇안되는 영화      1
9   5912145      왜케 평점이 낮은건데? 꽤 볼만한데.. 헐리우드식 화려함에만 너무 길들여져 있나?      1

In [104]:
test_data[:5]

        id                                           document  label
0  6270596                                                굳 ㅋ      1
1  9274899                               GDNTOPCLASSINTHECLUB      0
2  8544678             뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아      0
3  6825595                   지루하지는 않은데 완전 막장임... 돈주고 보기에는....      0
4  6723715  3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??      0

In [105]:
train_data = train_data.dropna(how = 'any')
train_data = train_data.reset_index(drop=True)
print(train_data.isnull().values.any())

False

In [106]:
test_data = test_data.dropna(how = 'any')
test_data = test_data.reset_index(drop=True)
print(train_data.isnull().values.any())

False

In [109]:
print(len(train_data))

149995

In [108]:
print(len(test_data))

49997

In [110]:
# 모델 불러오기
# multilingual : 다국가 언어를 번역할 수 있는 모델
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

C:\Project\Project_source\NLP_BERT\.venv\Lib\site-packages\huggingface_hub\file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

C:\Project\Project_source\NLP_BERT\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Win11Pro\.cache\huggingface\hub\models--bert-base-multilingual-cased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

In [111]:
print(tokenizer.encode("보는내내 그대로 들어맞는 예측 카리스마 없는 악역"))   # 토큰생성 후 숫자로 변환하는 과저ㅏㅇ

[101, 9356, 11018, 31605, 31605, 110589, 71568, 118913, 11018, 9576, 119281, 9786, 79940, 23811, 40364, 9520, 23160, 102]

In [112]:
print(tokenizer.tokenize("보는내내 그대로 들어맞는 예측 카리스마 없는 악역")) # 토큰 생성하는 과저 


# 토큰이 더 나눠졌다는 것은 서브 워드 토큰으로 나눠졌다는 것을 예측해 볼 수 있음!!

['보', '##는', '##내', '##내', '그대로', '들어', '##맞', '##는', '예', '##측', '카', '##리스', '##마', '없는', '악', '##역']

In [113]:
tokenizer.decode(tokenizer.encode("보는내내 그대로 들어맞는 예측 카리스마 없는 악역"))

'[CLS] 보는내내 그대로 들어맞는 예측 카리스마 없는 악역 [SEP]'

In [115]:
print(tokenizer.cls_token, ':', tokenizer.cls_token_id)
print(tokenizer.sep_token, ':', tokenizer.sep_token_id)
print(tokenizer.pad_token, ':', tokenizer.pad_token_id)

[CLS] : 101
[SEP] : 102
[PAD] : 0

In [116]:
max_seq_len =128

In [117]:
encoded_result = tokenizer.encode("전율을 일으키는 영화. 다시 보고싶은 영화", max_length=max_seq_len, pad_to_max_length=True)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
C:\Project\Project_source\NLP_BERT\.venv\Lib\site-packages\transformers\tokenization_utils_base.py:2645: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(

In [118]:
# 패딩을 확인해보자!!
# 뒤의 0이 모두 패딩이다
print(encoded_result)

[101, 9665, 119183, 10622, 9641, 119185, 66815, 42428, 119, 25805, 98199, 119088, 10892, 42428, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [119]:
print("길이 :", len(encoded_result))

길이 : 128

In [ ]:
# 입력을 할 때 문장이 필요하다 이때 세그먼트 입력을 해보자

In [120]:
print([0]*max_seq_len) # 0을 문장 길이만큼 반복함!

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [122]:
# 마스킹 작업
valid_num = len(tokenizer.encode("전율을 일으키는 영화. 다시 보고싶은 영화"))
print(valid_num * [1] + (max_seq_len - valid_num) * [0])

# 뒤에 0에는 마스킹 작업을 해준다!!

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [123]:
def convert_examples_to_features(examples, labels, max_seq_len, tokenizer):
    input_ids, attention_masks, token_type_ids, data_labels = [], [], [], []
    for example, label in tqdm(zip(examples, labels), total=len(examples)):
        input_id = tokenizer.encode(example, max_length=max_seq_len, pad_to_max_length=True)
        padding_count = input_id.count(tokenizer.pad_token_id)
        attention_mask = [1] * (max_seq_len - padding_count) + [0] * padding_count
        token_type_id = [0] * max_seq_len

        assert len(input_id) == max_seq_len, "Error with input length {} vs {}".format(len(input_id), max_seq_len)
        assert len(attention_mask) == max_seq_len, "Error with attention mask length {} vs {}".format(len(attention_mask), max_seq_len)
        assert len(token_type_id) == max_seq_len, "Error with token type length {} vs {}".format(len(token_type_id), max_seq_len)

        input_ids.append(input_id)
        attention_masks.append(attention_mask)
        token_type_ids.append(token_type_id)
        data_labels.append(label)

    input_ids = np.array(input_ids, dtype=int)
    attention_masks = np.array(attention_masks, dtype=int)
    token_type_ids = np.array(token_type_ids, dtype=int)

    data_labels = np.asarray(data_labels, dtype=np.int32)
    
    return (input_ids, attention_masks, token_type_ids), data_labels

    # (input_ids, attention_masks, token_type_ids) : 학습에 사용할 놈들
    # data_labels : 정답지

In [124]:
train_X, train_y = convert_examples_to_features(train_data['document'], train_data['label'],
                                               max_seq_len=max_seq_len, tokenizer=tokenizer)

100%|█████████████████████████████████████████████████████████████████| 149995/149995 [00:31<00:00, 4773.89it/s]

In [125]:
test_X, test_y = convert_examples_to_features(test_data['document'], test_data['label'],
                                                max_seq_len=max_seq_len, tokenizer=tokenizer)

100%|███████████████████████████████████████████████████████████████████| 49997/49997 [00:11<00:00, 4355.06it/s]

In [126]:
input_id = train_X[0][0]
attention_mask = train_X[1][0]
token_type_id = train_X[2][0]
label = train_y[0]

print("단어에 대한 정수 인코딩 :", input_id)
print("어텐션 마스크 :", attention_mask)
print("세그먼트 인코딩 :", token_type_id)
print("각 인코딩의 길이:", len(input_id))
print("정수 인코딩 복원 :", tokenizer.decode(input_id))
print("레이블 :", label)

단어에 대한 정수 인코딩 : [   101   9519   9074 119005    119    119   9708 119235   9715 119230
  16439  77884  48549   9284  22333  12692    102      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0]
어텐션 마스크 : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
세그먼트 인코딩 : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
각 인코딩의 길이: 128
정수 인코딩 복원 : [CLS] 아 더빙.. 진짜 짜증나네요 목소리 [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
레이블 : 0

In [127]:
model = TFBertModel.from_pretrained("bert-base-multilingual-cased")

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.

In [128]:
max_seq_len = 128

In [129]:
input_ids_layer = tf.keras.layers.Input(shape=(max_seq_len,), dtype=tf.int32)
attention_masks_layer = tf.keras.layers.Input(shape=(max_seq_len,), dtype=tf.int32)
token_type_ids_layer = tf.keras.layers.Input(shape=(max_seq_len,), dtype=tf.int32)

outputs = model([input_ids_layer, attention_masks_layer, token_type_ids_layer])

In [130]:
print(outputs)

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<KerasTensor: shape=(None, 128, 768) dtype=float32 (created by layer 'tf_bert_model')>, pooler_output=<KerasTensor: shape=(None, 768) dtype=float32 (created by layer 'tf_bert_model')>, past_key_values=None, hidden_states=None, attentions=None, cross_attentions=None)

In [133]:
print(outputs[0])

KerasTensor(type_spec=TensorSpec(shape=(None, 128, 768), dtype=tf.float32, name=None), name='tf_bert_model/bert/encoder/layer_._11/output/LayerNorm/batchnorm/add_1:0', description="created by layer 'tf_bert_model'")

In [134]:
print(outputs[1])

KerasTensor(type_spec=TensorSpec(shape=(None, 768), dtype=tf.float32, name=None), name='tf_bert_model/bert/pooler/dense/Tanh:0', description="created by layer 'tf_bert_model'")

In [135]:
#방금 만든 모델을 설계해보자!

In [137]:
class TFBertForSequenceClassification(tf.keras.Model):
    def __init__(self, model_name):
        super(TFBertForSequenceClassification, self).__init__()
        self.bert = TFBertModel.from_pretrained(model_name, from_pt=True)
        self.classifier = tf.keras.layers.Dense(1, 
                                                kernel_initializer=tf.keras.initializers.TruncatedNormal(0.02), 
                                                activation='sigmoid', 
                                                name='classifier')
    
    def call(self, inputs):
        input_ids, attention_mask, token_type_ids = inputs
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask, 
                            token_type_ids = token_type_ids)
        cls_token = outputs[1]
        prediction = self.classifier(cls_token)

        return prediction

In [138]:
model = TFBertForSequenceClassification("bert-base-multilingual-cased")
optimizer = tf.keras.optimizers.Adam(learning_rate=5e-5)
loss = tf. keras.losses. BinaryCrossentropy()
model.compile(optimizer=optimizer, loss=loss, metrics = ['accuracy'])

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

pytorch_model.bin:   0%|          | 0.00/714M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.

In [ ]:
model.fit(train_X, train_y,epochs=2, batch_size=64, validation_split=0.2)

Epoch 1/2
WARNING:tensorflow:From C:\Project\Project_source\NLP_BERT\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From C:\Project\Project_source\NLP_BERT\.venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

 464/1875 [======>.......................] - ETA: 5:51:04 - loss: 0.4778 - accuracy: 0.7640

In [ ]:
results = model.evaluate(text_X, test_y, batch_size=1024)
print("test loss, test acc: ", results)

In [ ]:
# 문장 예측
def sentiment_predict(new_sentence):
    input_id = tokenizer.encode(new_sentence, max_length=max_seq_len, pad_to_max_length=True)

    padding_count = input_id.count(tokenizer.pad_token_id)
    attention_mask = [1] * (max_seq_len - padding_count) + [0] * padding_count
    token_type_id = [0] * max_seq_len

    input_ids = np.array([input_id])
    attention_masks = np.array([attention_mask])
    token_type_ids = np.array([token_type_id])

    encoded_input = [input_ids, attention_masks, token_type_ids]
    score = model.predict(encoded_input)[0][0]                    # 예측
    print(score)

    if(score > 0.5):
        print("{:.2f}% 확률로 긍정 리뷰입니다.\n".format(score * 100))
    else:
        print("{:.2f}% 확률로 부정 리뷰입니다.\n".format((1 - score) * 100))

In [ ]:
sentiment_predict("보던거라 계속보고있는데 전개도 느리고 주인공인 은희는 한두컷 나오면서 소극적인모습에 ")